version: '3.9'

services:
  # signosp_frontend:
  #   container_name: FRONTEND
  #   build: ./signosp-frontend
  #   ports:
  #     - 5173:5173
  #   depends_on:
  #     - signosp_backend
  # signosp_backend:
  #   container_name: BACKEND
  #   image: signosp_backend:1.0.0
  #   build: ./signosp-backend
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - DATABASE_URL=jdbc:postgresql://0.0.0.0:5432/signosp_database
  #     - DATABASE_USERNAME=postgres
  #     - DATABASE_PASSWORD=postgres
  #   depends_on:
  #     - signosp_database
  signosp_database:
    container_name: signosp_database
    image: postgres:16.0
    build: ./signosp-bbdd
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signosp_database